---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: bits-service-release-version

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  VERSION_FILE:

outputs:
- name: assets

run:
  path: git-bits-service-release/ci/scripts/create-bits-release.sh
