---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release

outputs:
- name: manifests

run:
  path: git-bits-service-release/ci/scripts/create-colocated-cf-manifest.sh
