---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:

outputs:
- name: assets

run:
  path: git-bits-service-release/ci/scripts/create-release-and-manifest.sh
