---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: cf-release-version

outputs:
- name: manifests

params:
  VERSION_FILE: ../cf-release-version/number

run:
  path: git-bits-service-release/ci/scripts/create-colocated-cf-manifest.sh
