---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release
- name: manifests

params:
  BOSH_TARGET:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  MANIFEST_PATH:

run:
  path: git-bits-service-release/ci/scripts/deploy-release.sh
