---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release

params:
  BITS_SERVICE_ENDPOINT:
  BITS_SERVICE_MANIFEST:

run:
  path: git-bits-service-release/ci/scripts/run-tests.sh
