---
platform: linux

image: docker:///flintstonecf/ci

inputs:
- name: git-bits-service-release

params:
  BOSH_USERNAME:
  BOSH_PASSWORD:
  BOSH_TARGET:
  BITS_SERVICE_ENDPOINT:
  RELEASE_NAME:

run:
  path: git-bits-service-release/ci/scripts/run-tests.sh
