app_stash:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/app_stash
buildpacks:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/buildpacks
droplets:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/droplets
max_body_size: 2M
packages:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/packages

properties:
  bits-service:
    app_stash: &fog_connection
      fog_connection:
        provider: local
    buildpacks: *fog_connection
    droplets: *fog_connection
    packages: *fog_connection
