name: (( metadata.release_name ))
metadata:
  <<: (( merge ))
  release_name: bits-service
releases:
  - name: bits-service
    version: latest
compilation:
  workers: 1
  network: default
  cloud_properties:
    instance_type: m1.small
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1
networks: (( merge ))
resource_pools:
  - name: common
    network: default
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.small
      availability_zone:
      key_name:
jobs:
- name: bits-service
  template: bits-service
  instances: 1
  resource_pool: common
  networks:
  - name: default
properties:
  bits-service:
    <<: (( merge ))
    buildpacks:
      directory_key: (( merge ))
      fog_connection:
        <<: (( merge ))
