name: (( metadata.release_name ))

metadata:
  <<: (( merge ))
  release_name: bits-service

releases:
  - <<: (( merge ))
  - name: bits-service
    version: latest

networks: (( merge ))

resource_pools: (( merge ))

compilation:
  workers: 1
  network: default
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

jobs:
- <<: (( merge ))
- name: bits-service
  templates: 
  - name: bits-service
    release: bits-service
  instances: 1
  resource_pool: common
  networks:
  - name: default
    static_ips: (( static_ips(0) ))

properties:
  <<: (( merge ))
