metadata: (( merge ))

releases:
  - name: cf
    version: latest

networks: (( merge ))

resource_pools: (( merge ))

jobs:
  - name: blobstore
    templates:
    - name: blobstore
      release: cf
    instances: (( metadata.blobstore.instances || 0 ))
    resource_pool: common
    persistent_disk: 102400
    networks:
      - name: default
        static_ips: (( static_ips(1) ))
    update: {}

properties:
  system_domain: bosh-lite.com
  bits-service: (( merge ))
  blobstore:
    admin_users:
      - username: (( metadata.blobstore.username || "" ))
        password: (( metadata.blobstore.password || "" ))
    port: 80
    tls:
      port: 443
      cert: (( metadata.blobstore.tls.cert || "" ))
      private_key: (( metadata.blobstore.tls.private_key || "" ))
    secure_link:
      secret: blobstore-secret
