releases:
  - name: cf
    version: latest

jobs:
  - (( prepend ))
  - name: blobstore
    templates:
    - name: blobstore
      release: cf
    instances: (( grab metadata.blobstore.instances ))
    resource_pool: common
    persistent_disk: 102400
    networks:
      - name: default
        static_ips: (( static_ips(1) ))
    update: {}

properties:
  system_domain: bosh-lite.com
  blobstore:
    admin_users:
      - username: (( grab metadata.blobstore.username || "" ))
        password: (( grab metadata.blobstore.password || "" ))
    port: 8080
    tls:
      port: 4443
      cert: (( grab metadata.blobstore.tls.cert || "" ))
      private_key: (( grab metadata.blobstore.tls.private_key || "" ))
    secure_link:
      secret: blobstore-secret
