meta:
  releases:
  - name: bits-service
    version: <%= ENV.fetch('RELEASE_VERSION', 'latest') %>
releases:
- name: bits-service
  version: <%= ENV.fetch('RELEASE_VERSION', 'latest') %>
jobs:
- instances: 1
  name: bits_service_z1
  networks:
  - name: cf1
    static_ips:
    - 10.244.0.74
  persistent_disk: 6064
  resource_pool: small_z1
  templates:
  - name: bits-service
    release: bits-service
  update:
    max_in_flight: 1
    serial: true
properties:
  cc:
    bits_service:
      enabled: true
      endpoint: http://10.244.0.74
