meta:
  releases:
  - name: bits-service
    version: <%= ENV.fetch('RELEASE_VERSION', 'latest') %>
releases:
- name: bits-service
  version: <%= ENV.fetch('RELEASE_VERSION', 'latest') %>
jobs:
- (( merge on name ))
- name: blobstore_z1
  instances: 1
  networks:
  - name: cf1
    static_ips: null
  persistent_disk: 102400
  properties:
    consul:
      agent:
        services:
          blobstore: {}
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: blobstore
        port: 80
        registration_interval: 20s
        tags:
          component: blobstore
        uris:
        - blobstore.bosh-lite.com
  resource_pool: small_z1
  templates:
  - name: consul_agent
    release: cf
  - name: metron_agent
    release: cf
  - name: blobstore
    release: cf
  - name: route_registrar
    release: cf
  update: {}
- name: bits_service_z1
  instances: 1
  networks: []
  persistent_disk: 6064
  resource_pool: small_z1
  templates:
  - name: bits-service
    release: bits-service
  - name: route_registrar
    release: cf
  - name: consul_agent
    release: cf
  properties:
    consul:
      agent:
        services:
          bits-service: {}
    route_registrar:
      routes:
      - name: bits-service
        port: 80
        registration_interval: 20s
        tags:
          component: bits-service
        uris:
        - (( concat "bits-service." properties.system_domain ))
  update:
    max_in_flight: 1
    serial: true
properties:
  cc:
    bits_service:
      enabled: true
      public_endpoint: (( concat "http://bits-service." properties.system_domain ))
      private_endpoint: http://bits-service.service.cf.internal
